import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export default class PrismaService extends PrismaClient {
    // PrismaClient instance is automatically generated by Prisma
    // We can use this instance to interact with our database
    // For example, we can use this instance to query the database for data
    // or to update data in the database
    constructor() {
        super();
        this.$connect();
    }
}
